#!/bin/bash

# Detect Linux distribution
detect_linux_distribution() {
    if [[ -f /etc/redhat-release ]]; then
        _release="centos"
    elif grep -qiE "debian|ubuntu" /etc/issue; then
        _release="debian"
    elif grep -qiE "centos|red hat|redhat" /etc/issue; then
        _release="centos"
    elif grep -qiE "debian|ubuntu" /proc/version; then
        _release="debian"
    elif grep -qiE "centos|red hat|redhat" /proc/version; then
        _release="centos"
    else
        echo -e "${RED}CentOS, Debian, or Ubuntu not detected. The script may not work correctly.${RESET}"
        exit 1
    fi
}

# Function to display usage message
show_usage() {
    echo "Usage: cachecln <value> ramtrig <value>"
    echo "Example: cachecln 2 ramtrig 45"
    exit 1
}

# Function to start the auto-clean.sh script
autoclean_start() {
    # Check if the script is already running
    if pgrep auto-clean.sh > /dev/null; then
        echo "The script is already running."
    else
        /etc/init.d/auto-clean.sh
    fi
}

# Function to stop the auto-clean.sh script
autoclean_stop() {
    pkill auto-clean.sh > /dev/null 2>&1
    echo "Script stopped."
}

# Function to restart the auto-clean.sh script
autoclean_restart() {
    pkill auto-clean.sh
    autoclean_start
}

# Function to remove the auto-clean.sh script
autoclean_remove() {
    if [[ $_release = centos ]]; then
        service auto-clean.sh stop > /dev/null 2>&1
        chkconfig --del auto-clean.sh > /dev/null 2>&1
        rm -rf /etc/init.d/auto-clean.sh
        pkill auto-clean.sh > /dev/null 2>&1
        rm -rf /usr/local/bin/autoclean
        echo "The script was removed."
    elif [[ $_release = debian ]] || [[ $_release = ubuntu ]]; then
        update-rc.d -f auto-clean.sh remove > /dev/null 2>&1
        rm -rf /etc/init.d/auto-clean.sh
        pkill auto-clean.sh > /dev/null 2>&1
        rm -rf /usr/local/bin/autoclean
        echo "The script was removed."
    fi
}

# Function to display trigger values
trig_values() {
    echo "cachecln: $cache_cln"
    echo "ramtrig: $ram_trig"
}

# Path to the auto-clean.sh script
script_path="/etc/init.d/auto-clean.sh"

# Process the parameters
while [ "$#" -gt 0 ]; do
    case "$1" in
        cachecln)
            # Check if the second argument is a number between 1 and 3
            if ! [[ "$2" =~ ^[1-3]$ ]]; then
                echo "Invalid value for cachecln. It must be a number between 1 and 3."
                show_usage
            fi
            sed -i "s/_cache_cln=.*/_cache_cln=$2/" "$script_path"
            cache_cln="$2"
            shift 2
            ;;
        ramtrig)
            # Check if the second argument is a number between 5 and 90
            if ! [[ "$2" =~ ^[5-9]|[1-8][0-9]|90$ ]]; then
                echo "Invalid value for ramtrig. It must be a number between 5 and 90."
                show_usage
            fi
            sed -i "s/_ram_trig=.*/_ram_trig=$2/" "$script_path"
            ram_trig="$2"
            autoclean_restart
            trig_values
            shift 2
            ;;
        start)
            autoclean_start
            break
            ;;
        stop)
            autoclean_stop
            break
            ;;
        restart)
            autoclean_restart
            break
            ;;
        remove)
            detect_linux_distribution
            autoclean_remove
            break
            ;;
        *)
            show_usage
            ;;
    esac
done
