#!/bin/bash

if [[ -f /etc/redhat-release ]]; then
	 _release="centos"
elif cat /etc/issue | grep -q -E -i "debian"; then
	 _release="debian"
elif cat /etc/issue | grep -q -E -i "ubuntu"; then
   _release="ubuntu"
elif cat /etc/issue | grep -q -E -i "centos|red hat|redhat"; then
	 _release="centos"
elif cat /proc/version | grep -q -E -i "debian"; then
	 _release="debian"
elif cat /proc/version | grep -q -E -i "ubuntu"; then
	 _release="ubuntu"
elif cat /proc/version | grep -q -E -i "centos|red hat|redhat"; then
	 _release="centos"
fi

if [[ $_release = centos ]]; then
  service auto-clean.sh stop > /dev/null 2>&1
  chkconfig --del auto-clean.sh > /dev/null 2>&1
  rm -rf /etc/init.d/auto-clean.sh
  killall auto-clean.sh > /dev/null 2>&1
elif [[ $_release = debian ]] || [[ $_release = ubuntu ]]; then
  update-rc.d -f auto-clean.sh remove > /dev/null 2>&1
  rm -rf /etc/init.d/auto-clean.sh
  killall auto-clean.sh > /dev/null 2>&1
fi

rm -rf /bin/start-auto
rm -rf /bin/stop-auto
rm -rf /bin/rm-auto
